### ISSUE TITLE
One tip

### ISSUE THREAD

**Issue by Drintau** [flikas/archived-idea-spring-boot-assistant#1]
I guess you are Chinese too,so i will speak Chinese.
一个建议：之前一直在用这位作者修改后的[插件](https://github.com/eltonsandre/intellij-spring-assistant)，因为没有上架idea插件市场很不方便，您上架了插件市场真是帮助了许多人，非常感谢。那位作者的更新挺勤快的，可能有一些值得借鉴的地方。
只是一个建议，没有别的意思。原谅我英语比较差~

**Comment by Drintau** [comment]
这不是一个issue，关闭。作者看后可以删除了哦~

**Comment by flikas** [comment]
嗯嗯，我会持续关注他们的更新。
