### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by shasureshkumar** [flikas/archived-idea-spring-boot-assistant#2]
Hi, I am using Intellij 2021.2.3, I came across this plugin recently and installed this on my IDE, but its not suggesting anything in the yml file. The suggestion is working for application.properties but not on the application.yml file. Am I doing anything wrong here?

<img width="454" alt="Screenshot 2021-12-06 at 2 38 13 PM" src="https://user-images.githubusercontent.com/11661366/144818652-9e8d8912-f1bd-40f8-a42d-10e15437f75b.png">

**Comment by flikas** [comment]
It looks like your `application.yml` file didn't be opened as a yaml file.
Try Settings->Editor->File Types

**Comment by shasureshkumar** [comment]
yeah.. you are right. It works now. Thanks... we can close this.
