### ISSUE TITLE
CTRL+SPACE, can i define it to others?

### ISSUE THREAD

**Issue by aaric** [flikas/archived-idea-spring-boot-assistant#3]
> Suggestions would appear as soon as you type/press `CTRL+SPACE`.

Windows被限制用于输入法大小切换，而且不能修改，是否可以设置其他？

**Comment by flikas** [comment]
都可以改的，Windows在输入法设置里改。IDEA在 Settings->Keymap 里改。

**Comment by aaric** [comment]
在IDEA在 Settings->Keymap 没有发现Spring Boot Assistant的快捷键路径（特别是在Plugins目录），能否提供一下？谢谢

**Comment by flikas** [comment]
Keymap里的 Main Menu->Code->Code Completion->Basic

**Comment by aaric** [comment]
问题解决了，非常感谢大神！
