### ISSUE TITLE
yaml文件属性悬浮文档中的中文乱码问题

### ISSUE THREAD

**Issue by shilohooo** [flikas/archived-idea-spring-boot-assistant#6]
- 属性配置
![9c6c09a539678dc39b4af35e99f0c6e](https://user-images.githubusercontent.com/46670399/153562144-f95c9411-4f15-4b19-b804-c969637b79c3.png)

- 问题截图
![193fab4f24cbc028e24dac0853b7b41](https://user-images.githubusercontent.com/46670399/153562166-01ca048a-6cd8-49a2-a8ae-f2e4fd690d23.png)

**Comment by flikas** [comment]
看起来是字符集问题？大概是您的metadata文件的编码与IDE不一致导致的。我尝试优化一下这方面的兼容性。

**Comment by shilohooo** [comment]
> 看起来是字符集问题？大概是您的metadata文件的编码与IDE不一致导致的。我尝试优化一下这方面的兼容性。

IDE这边我用的是UTF-8，metadata文件是在/.idea/文件夹里面吗

**Comment by flikas** [comment]
请查看 `target/classes/META-INF/spring-configuration-metadata.json` 这个文件，看看里面对应的属性说明是否是乱码。
以及这个文件的字符集编码，以及源代码文件`ScheduleConfig.java`的字符集编码。

**Comment by geektao** [comment]
目前可以IDEA启动指定文件编码：打开IDEA的安装目录，在bin目录下，找到idea64.exe.vmoptions、idea.exe.vmoptions这两个文件，在文件末尾追加-Dfile.encoding=UTF-8 。 亲测有效

**Comment by ljchen1** [comment]
你好，你可以使用附件的这个项目在 Windows 10 的中文系统上复现这个问题（无法在 Linux 上复现）。打开  src/main/resources/application.yml ，在 `uri` 上 Ctrl+Q 使用 Quick Documentation 看文档，在安装了这个插件后内容就会变成乱码了（停用 idea-spring-boot-assistant 插件的话，就正常了）
另外 spring-configuration-metadata.json 文件是 utf-8 编码的。

如果 @geektao 上面的加 -Dfile.encoding=UTF-8 有用的话，有可能是插件哪里做了点编码转换，把 utf-8 文字转成了 gbk 导致乱码了。
另外也可以通过 IDE 主菜单上的 `Help | Edit Custom VM Options...` 加这个。如果直接改安装目录下的文件，升级 IDE 的时候，增量更新的时候可能会无法更新这两个文件成功。

[demo3.zip](https://github.com/flikas/idea-spring-boot-assistant/files/9189585/demo3.zip)
